kube-prometheus-stack:
  nameOverride: "kps"
  fullnameOverride: "kps"
  prometheus-node-exporter:
    hostRootFsMount: false
  alertmanager:
    enabled: true
    alertmanagerSpec:
      useExistingSecret: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - alertmanager.happyhippo.local
      paths: []
      tls: 
      - secretName: happyhippo-local-tls
        hosts:
        - alertmanager.happyhippo.local
  
  grafana:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.happyhippo.local
      path: /
      tls: 
      - secretName: happyhippo-local-tls
        hosts:
        - grafana.happyhippo.local
  
  prometheus:
    enabled: true
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - prometheus.happyhippo.local
      path: /
      tls: 
      - secretName: happyhippo-local-tls
        hosts:
        - prometheus.happyhippo.local

