kube-prometheus-stack:
  nameOverride: "kps"
  fullnameOverride: "kps"
  prometheus-node-exporter:
    hostRootFsMount: false
  alertmanager:
    enabled: true
    config:
        global:
          resolve_timeout: 1m
          slack_api_url: 'https://hooks.slack.com/services/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'
          route:
             receiver: 'slack-galsolom-argo'
          receivers:
          - name: 'slack-galsolom-argo'
          slack_configs:
          - channel: '#alert-tests'
            send_resolved: true

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts: 
        - alertmanager.happyhippo.local
      paths: []
      tls: 
      - secretName: happyhippo-local-tls
        hosts:
        - alertmanager.happyhippo.local
  grafana:
    enabled: true

    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.happyhippo.local
      path: /
      tls: 
      - secretName: happyhippo-local-tls
        hosts:
        - grafana.happyhippo.local

