apiVersion: v2
name: metallb
description: bare-metal load balancer
type: application
version: 0.11.0
appVersion: 0.11.0

dependencies:
- name: ingress-nginx
  version: 4.0.17
  repository: https://kubernetes.github.io/ingress-nginx