
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argo
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    helm:
      releaseName: apps
      version: v3
      valueFiles:
          - values.yaml
    path: argo/apps
    repoURL: https://github.com/galsolom/argo
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true


