apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argo
spec:
  project: default
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    helm:
      releaseName: platform-apps
      version: v3
      valueFiles:
          - values.yaml
    path: argo/platform-apps
    repoURL: {{ .Values.repo.url }}
    targetRevision: {{ .Values.repo.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
