apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argo
spec:
  project: {{ $.Values.spec.project }}
  destination:
    namespace: argo
    server: {{ $.Values.spec.destination.server }}
  source:
    helm:
      releaseName: platform-apps
      version: v3
      valueFiles:
          - values.yaml
    path: argo/platform-apps
    repoURL:  {{ $.Values.spec.destination.server }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
