apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argo
spec:
  project: {{ .Values.spec.project }}
  destination:
    namespace: argo
    server: {{ .Values.spec.destination.server }}
  source:
    helm:
      releaseName: argocd
      version: v3
      valueFiles:
          - values.yaml
    path: argocd/apps/argocd
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

