{{- range $application := .Values.enabledApplications }}
{{- if $application.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}
  namespace: argo
  annotations:
  {{- if $application.url }}
    link.argocd.argoproj.io/external-link: https://{{ $application.url }}{{$.Values.spec.domain}}
  {{- end }}
  {{- if $application.syncWave }}
    argocd.argoproj.io/sync-wave: "{{ $application.syncWave }}"
  {{- end }}
spec:
  project: {{ $.Values.spec.project }}
  destination:
    namespace: {{ $application.namespace }}
    server: {{ $.Values.spec.destination.server }}
  source:
  {{- if $application.plugin }}
    plugin:
      name: helmfile
      env:
      - name: CLUSTER_ID
        value: primary
      - name: HELMFILE_GLOBAL_OPTIONS
        value: --environment {{ $.Values.helmfile.env }}
  {{- else }}
    helm:
      releaseName: {{ $application.name }}
    {{- if $application.skipCrds }}
      skipCrds: true
    {{- end }}
      version: v3
      valueFiles:
          - values.yaml
  {{- end }}
    path: argo/{{ $application.name }}
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
{{- end }}
---
{{- end }}

