apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
  name: helm-test
  namespace: argo
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./argo/helmfile-test
    plugin:
      env:
      - name: CLUSTER_ID
        value: primary
      - name: HELMFILE_GLOBAL_OPTIONS
        value: --environment dev
      name: helmfile
    repoURL: {{ $.Values.spec.source.repoURL }}
    targetRevision: {{ $.Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
