# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   labels:
#   name: helm-test
#   namespace: argo
# spec:
#   project: {{ $.Values.spec.project }}
#   destination:
#     namespace: default
#     server: {{ $.Values.spec.destination.server }}
#   source:
#     path: ./argo/helmfile-test
#     plugin:
#       name: helmfile
#       env:
#       - name: CLUSTER_ID
#         value: primary
#       - name: HELMFILE_GLOBAL_OPTIONS
#         value: --environment {{ $.Values.helmfile.env }}
#     repoURL: {{ $.Values.spec.source.repoURL }}
#     targetRevision: {{ $.Values.spec.source.targetRevision }}
#   syncPolicy:
#     syncOptions:
#     - ApplyOutOfSyncOnly=true
