# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: keda
#   namespace: argo
# spec:
#   project: {{ .Values.spec.project }}
#   destination:
#     namespace: keda
#     server: {{ .Values.spec.destination.server }}
#   source:
#     helm:
#       releaseName: keda
#       version: v3
#       valueFiles:
#           - values.yaml
#     path: argo/keda
#     repoURL: {{ .Values.spec.source.repoURL }}
#     targetRevision: {{ .Values.spec.source.targetRevision }}
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true

