apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: minio
  annotations:
    link.argocd.argoproj.io/external-link: https://minio{{.Values.spec.domain}}
spec:
  project: {{ .Values.spec.project }}
  destination:
    namespace: minio
    server: {{ .Values.spec.destination.server }}
  source:
    helm:
      releaseName: minio
      version: v3
      valueFiles:
          - values.yaml
    path: argo/minio
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

