keycloak:
  ingress:
    enabled: true
    ingressClassName: "nginx"
    servicePort: http
    annotations: 
      nginx.ingress.kubernetes.io/proxy-buffer-size: 128k
    labels: {}
    rules:
      -
        host: keycloak.gals.local
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - keycloak.gals.local
        secretName: "gals-local-tls"

    console:
      enabled: true
      ingressClassName: "nginx"
      annotations: {}
      rules:
        -
          host: keycloakconsole.gals.local
          paths:
            - path: /auth/admin/
              pathType: Prefix
      tls:
      - hosts:
          - keycloakconsole.gals.local
        secretName: "gals-local-tls"