apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: selenium-grid-chrome-scaledobject
  namespace: selenium
  labels:
    deploymentName: selenium-chrome-node
spec:
  maxReplicaCount: 8
  pollingInterval: 5  # Optional. Default: 30 seconds
  cooldownPeriod:  30 # Optional. Default: 300 seconds
  minReplicaCount: 1  # Optional. Default: 0

  scaleTargetRef:
    name: selenium-chrome-node
  triggers:
    - type: selenium-grid
      metadata:
        url: 'selenium-router.selenium:4444'
        browserName: 'chrome'