---
bases:
  - "../bases/environments.yaml"
  - "../bases/repos.yaml"
---

releases:
{{- if .Environment.Values.autoscaler.enabled | default false }}
- name: "cluster-autoscaler-{{ .Environment.Name }}"
  namespace: "autoscaler"
  chart: "stable/cluster-autoscaler"
  labels:
    chart: "cluster-autoscaler"
    repo: "stable"
    namespace: "kube-system"
  version: 8.0.0
  values:
    - "./values/common/cluster-autoscaler-values.yaml.gotmpl"

{{ end }}

- name: "kube-dashboard-{{ .Environment.Name }}"
  namespace: "default"
  chart: "kubernetes-dashboard/kubernetes-dashboard"
  labels:
    chart: "kubernetes-dashboard"
    repo: "kubernetes-dashboard"
    namespace: "default"
  version: 5.4.1
  values:
    - "./values/{{ .Environment.Name }}/dashboard-values.yaml"

- name: "redis-{{ .Environment.Name }}"
  namespace: "default"
  chart: "bitnami/redis"
  labels:
    chart: "bitnami"
    repo: "redis"
    namespace: "default"
  version: 16.8.5
  values:
    - "./values/{{ .Environment.Name }}/redis-values.yaml"

