image:
  repo: docker.io/galsolom/app
  tag: main-0068bde3881ecdbd4f3b2235cb7fa9f9f9f2baa5
ingressHost: app
port: 80
replicas: 3
requests:
  cpu: 100m
  memory: 50Mi
limits:
  cpu: 250m
  memory: 250Mi
