image:
  repo: docker.io/galsolom/app
  tag: main-df1e12e1d4271df86d2cb6073f0e0e767f273f88
ingressHost: app
port: 80
replicas: 3
requests:
  cpu: 100m
  memory: 50Mi
limits:
  cpu: 250m
  memory: 250Mi
