image:
  repo: docker.io/galsolom/app
  tag: main-147c8e4d56f323c4d525d1ba46ef0e0a730900a4
ingressHost: app
port: 80
replicas: 3
requests:
  cpu: 100m
  memory: 50Mi
limits:
  cpu: 250m
  memory: 250Mi
