image:
  repo: docker.io/galsolom/app
  tag: main-2c3fffd1c9a47fd2456e345068951a10d06b52c9
ingressHost: app
port: 80
replicas: 3
requests:
  cpu: 100m
  memory: 50Mi
limits:
  cpu: 250m
  memory: 250Mi
