apiVersion: v2
appVersion: v2.4.6
description: A Helm chart for ArgoCD, a declarative, GitOps continuous delivery tool for Kubernetes.
name: argo-cd
version: 4.9.14
home: https://github.com/argoproj/argo-helm
icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
keywords:
  - argoproj
  - argocd
  - gitops
maintainers:
  - name: alexec
  - name: alexmt
  - name: jessesuen
  - name: seanson
dependencies:
  - name: redis-ha
    version: 4.17.1
    repository: https://dandydeveloper.github.io/charts/
    condition: argo-cd.redis-ha.enabled
  - name: argo-cd
    version: 4.9.14
    repository: https://argoproj.github.io/argo-helm/

