repo:
  url: &url https://github.com/galsolom/argo
  targetRevision: main

argo-cd:
  server:
    extraArgs: 
    - --insecure

    ingress:
      enabled: true
      ingressClassName: "nginx"

      hosts:
        - argocd.gals.local

      paths:
        - /
      pathType: Prefix
      extraPaths: []

      tls:
        - secretName: gals-local-tls
          hosts:
            - argocd.gals.local

  configs:
    repositories: 
      repo:
        url: *url
