repo:
  url: &url https://github.com/galsolom/argo
  targetRevision: main

argo-cd:
  server:
    extraArgs: 
    - --insecure

    ingress:
      enabled: true
      ingressClassName: "nginx"

      hosts:
        - argocd.happyhippo.local

      paths:
        - /
      pathType: Prefix
      extraPaths: []

      tls:
        - secretName: happyhippo-local-tls
          hosts:
            - argocd.happyhippo.local

  configs:
    repositories: 
      repo:
        url: *url
  
  metrics:
  # -- Deploy metrics service
  enabled: true
  service:
    # -- Metrics service annotations
    annotations: {}
    # -- Metrics service labels
    labels: {}
    # -- Metrics service port
    servicePort: 8083
  serviceMonitor:
    # -- Enable a prometheus ServiceMonitor
    enabled: true
    # -- Prometheus ServiceMonitor interval
    interval: 30s
    # -- Prometheus [RelabelConfigs] to apply to samples before scraping
    relabelings: []
    # -- Prometheus [MetricRelabelConfigs] to apply to samples before ingestion
    metricRelabelings: []
    # -- Prometheus ServiceMonitor selector
    selector: {}
      # prometheus: kube-prometheus

    # -- Prometheus ServiceMonitor namespace
    namespace: ""  # monitoring
    # -- Prometheus ServiceMonitor labels
    additionalLabels: {}

