metrics-server:
  defaultArgs:
    - --cert-dir=/tmp
    - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
    - --kubelet-use-node-status-port
    - --metric-resolution=90s
    - --kubelet-insecure-tls
    - --kubelet-preferred-address-types=InternalIP

