apiVersion: v2
name: metallb
description: bare-metal load balancer
type: application
version: 0.11.0
appVersion: 0.11.0

dependencies:
- name: metallb
  version: 0.11.0 
  repository: https://metallb.github.io/metallb