metallb:
  configInline:
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 127.0.0.241-127.0.0.250
    - name: ingress
      protocol: layer2
      addresses:
      - 127.0.0.240/32