apiVersion: v2
name: kube-state-metrics
type: application
version: 2.2.4
appVersion: 2.3.0
home: https://github.com/kubernetes/kube-state-metrics/
sources:
- https://github.com/kubernetes/kube-state-metrics/
dependencies:
  - name: kube-state-metrics
    version: 2.2.4
    repository: https://charts.bitnami.com/bitnami

