spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    # your fork url
    repoURL: https://github.com/galsolom/argo
    targetRevision: main
  project: default
  domain: .happyhippo.local

helmfile:
  env: dev

enabledApplications:
  - name: argocd
    enabled: true
    namespace: argo
    url: argocd
    #
  - name: helmfile
    enabled: true
    namespace: default
    plugin: helmfile
    #
  - name: argoworkflows
    enabled: false
    namespace: argo
    url: argoworkflows
    #
  - name: prometheus
    enabled: true
    namespace: prometheus
    url: grafana
    skipCrds: true
    syncWave: 2
    #
  - name: metrics-server
    enabled: true
    namespace: metrics
    #
  - name: minio
    enabled: false
    namespace: minio
    url: consoleminio
    #
  - name: keda
    enabled: false
    namespace: keda
    #
  - name: keycloak
    enabled: false
    url: keycloak
    namespace: keycloak
# network
  - name: metallb
    enabled: true
    namespace: metallb-system
    #
  - name: ingress-nginx
    enabled: true
    namespace: ingress-nginx
