spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/galsolom/argo
    targetRevision: main
  project: default
  domain: .gals.local

enabledApplications:
  - name: argocd
    enabled: true
    namespace: argo
    url: argocd
  - name: argoworkflows
    enabled: true
    namespace: argo
    url: argoworkflows
  - name: prometheus
    enabled: true
    namespace: prometheus
    url: grafana
  - name: minio
    enabled: true
    namespace: minio
    url: consoleminio
  - name: keda
    enabled: true
    namespace: keda