apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  annotations:
    argocd.argoproj.io/sync-wave: "-100"
spec:
  project: {{ .Values.spec.project }}
  destination:
    namespace: prometheus
    server: {{ .Values.spec.destination.server }}
  source:
    repoURL: https://github.com/galsolom/argo.git
    path: argo/prometheus/crd-override
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Replace=true
    - CreateNamespace=true